language: java

dist: trusty

env:
  global:
  - LTSMIN_VERSION="v3.1.0"

cache:
  directories:
  - $HOME/.m2
  - $HOME/ltsmin

install:
  # install LTSmin
  - ${TRAVIS_BUILD_DIR}/install-ltsmin.sh
  - PATH="$PATH:$HOME/ltsmin/$LTSMIN_VERSION/bin"
  # override any "sane" defaults of Travis VMs
  - mkdir -p ${HOME}/.m2
  - cp ${TRAVIS_BUILD_DIR}/.travis/settings.xml ${HOME}/.m2/settings.xml

script:
  - ltsmin-convert --version || true
  - mvn --version
  - mvn install -B

jobs:
  fast_finish: true
  include:
    # First stage
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk11
    - stage: Integration Test
      jdk: openjdk11
      env: MAVEN_OPTS="$MAVEN_OPTS -Dmaven.compiler.source=11 -Dmaven.compiler.target=11"
    - os: osx
      jdk: openjdk8
    - os: osx
      jdk: openjdk11
    - os: windows
      jdk: oraclejdk8
      language: shell
      before_install:
        - cinst jdk8 -params 'installdir=C:\\jdk8'
        - export JAVA_HOME="C:\jdk8"
        - export PATH=${JAVA_HOME}/bin:${PATH}
        - cinst maven -params 'installdir=C:\\maven'
    - os: windows
      jdk: oraclejdk11
      language: shell
      before_install:
      - cinst jdk11 -params 'installdir=C:\\jdk11'
      - export JAVA_HOME="C:\jdk11"
      - export PATH=${JAVA_HOME}/bin:${PATH}
      - cinst maven -params 'installdir=C:\\maven'
    - stage: Deploy
      jdk: openjdk11
      script: true
