language: java

dist: trusty

env:
  global:
  - LTSMIN_VERSION="v3.1.0"

cache:
  directories:
  - $HOME/.m2
  - $HOME/ltsmin

install:
  # install LTSmin
  - ${TRAVIS_BUILD_DIR}/install-ltsmin.sh
  - PATH="$PATH:$HOME/ltsmin/$LTSMIN_VERSION/bin"
  # override any "sane" defaults of Travis VMs
  - mkdir -p ${HOME}/.m2
  - cp ${TRAVIS_BUILD_DIR}/.travis/settings.xml ${HOME}/.m2/settings.xml

script:
  - ltsmin-convert --version || true
  - mvn --version
  - mvn install -B

jobs:
  fast_finish: true
  include:
    - stage: 1st Stage
    - jdk: openjdk8
    - jdk: openjdk11
    - stage: 2nd Stage
      jdk: openjdk11
      env: MAVEN_OPTS="$MAVEN_OPTS -Dmaven.compiler.source=11 -Dmaven.compiler.target=11"
    - os: osx
      jdk: openjdk8
      # Force old xcode image so JDK8 isn't overridden from newer xcode version
      osx_image: xcode9.3
    - os: osx
      jdk: openjdk11
    - os: windows
      jdk: oraclejdk8
      language: shell
      before_install:
        - export JAVA_HOME="/c/Program Files/Java/jdk1.8.0_192"
        - export PATH=${JAVA_HOME}/bin:${PATH}
        - cinst maven -params 'installdir=C:\\maven'
    - os: windows
      jdk: oraclejdk11
      language: shell
      before_install:
      - cinst jdk11 -params 'installdir=C:\\jdk11'
      - export JAVA_HOME="C:\jdk11"
      - export PATH=${JAVA_HOME}/bin:${PATH}
      - cinst maven -params 'installdir=C:\\maven'
      script: produce-error-by-calling-a-program-that-does-not-exist
    - stage: 3rd Stage
      jdk: openjdk11
      script: true
  allow_failures:
    - os: windows
      jdk: oraclejdk10
