language: java

dist: trusty
sudo: true

env:
  global:
  - LTSMIN_VERSION="v3.1.0"

cache:
  directories:
  - $HOME/.m2
  - $HOME/ltsmin

install:
  # install LTSmin
  - ${TRAVIS_BUILD_DIR}/install-ltsmin.sh
  - PATH="$PATH:$HOME/ltsmin/$LTSMIN_VERSION/bin"
  # override any "sane" defaults of Travis VMs
  - mkdir -p ${HOME}/.m2
  - cp ${TRAVIS_BUILD_DIR}/.travis/settings.xml ${HOME}/.m2/settings.xml

script:
  - ltsmin-convert --version || true
  - mvn --version
  - mvn install -B

jobs:
  fast_finish: true
  include:
#    - jdk: openjdk8
#    - jdk: openjdk11
#    - stage: Integration Test
#      jdk: openjdk11
#      env: MAVEN_OPTS="$MAVEN_OPTS -Dmaven.compiler.source=11 -Dmaven.compiler.target=11"
#    - os: osx
#      jdk: openjdk8
#      # Force old xcode image so JDK8 isn't overridden from newer xcode version
#      osx_image: xcode9.3
#    - os: osx
#      jdk: openjdk11
    - os: windows
      jdk: oraclejdk8
      language: shell
      before_install:
      - export JAVA_HOME="C:\Program Files\Java\jdk1.8.0"
      - export PATH=${JAVA_HOME}/bin:${PATH}
      - ls /bin
      - ls /cmd
      - ls /etc
      - ls /usr
      - find /
      - pwd
      - java -version
      - cinst maven -params 'installdir=C:\\maven'
#    - os: windows
#      jdk: oraclejdk10
#      language: shell
#      before_install:
#      - export JAVA_HOME="C:\Program Files\Java\jdk10"
#      - export PATH=${JAVA_HOME}/bin:${PATH}
#      - ls /bin
#      - ls /cmd
#      - ls /etc
#      - ls /usr
#      - find /
#      - pwd
#      script:
#        - java -version
#        - produce-error-by-calling-a-program-that-does-not-exist
#    - os: windows
#      jdk: oraclejdk11
#      language: shell
#      before_install:
#      - ls /bin
#      - ls /cmd
#      - ls /etc
#      - ls /usr
#      - find /
#      - pwd
#      - cinst jdk11 -params 'installdir=C:\\jdk11'
#      - export JAVA_HOME="C:\jdk11"
#      - export PATH=${JAVA_HOME}/bin:${PATH}
#      - cinst maven -params 'installdir=C:\\maven'
#    - stage: Deploy
#      jdk: openjdk11
#      script: true
#  allow_failures:
#    - os: windows
#      jdk: oraclejdk10
